name: Deploy and Release

on:
  push:
    branches:
      - main

jobs:
  build-deploy-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Adjust if you need a different version

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build
      
    - name: Deploy to page branch
      run: |
        cd dist
        git init
        git add -A
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git config --local --add safe.directory /github/workspace/dist
        git commit -m 'deploy'
        
    - name: Force push to destination branch
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        force: true
        directory: ./dist
